services:
  # server:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
